# Generated by Django 4.2.7 on 2026-08-05 16:56

import apps.accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=80, verbose_name="Фамилия"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Ученик"),
                            ("teacher", "Преподаватель"),
                            ("owner", "Владелец"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=16,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="Фото"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Krasnoyarsk",
                        max_length=64,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "telegram_link_code",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления на email"
                    ),
                ),
                (
                    "notify_telegram",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления в Telegram"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Лид"),
                            ("trial", "Пробный урок"),
                            ("active", "Учится"),
                            ("paused", "Пауза"),
                            ("churned", "Ушёл"),
                        ],
                        db_index=True,
                        default="lead",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A0", "A0 · Beginner"),
                            ("A1", "A1 · Elementary"),
                            ("A2", "A2 · Pre-Intermediate"),
                            ("B1", "B1 · Intermediate"),
                            ("B2", "B2 · Upper-Intermediate"),
                            ("C1", "C1 · Advanced"),
                            ("C2", "C2 · Proficiency"),
                        ],
                        max_length=2,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("goal", models.TextField(blank=True, verbose_name="Цель обучения")),
                (
                    "parent_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Родитель / контактное лицо",
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон родителя"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Откуда узнал"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Заметки администратора"),
                ),
                (
                    "started_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало обучения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль ученика",
                "verbose_name_plural": "Профили учеников",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Специализация"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "experience_since",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="В профессии с"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Образование"
                    ),
                ),
                (
                    "is_native",
                    models.BooleanField(default=False, verbose_name="Носитель языка"),
                ),
                (
                    "show_on_site",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "accepts_new_students",
                    models.BooleanField(default=True, verbose_name="Набирает учеников"),
                ),
                ("calendar_color", models.CharField(default="#0B6E7F", max_length=7)),
                (
                    "pay_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Используется для расчёта зарплаты в отчётах владельца.",
                        max_digits=9,
                        verbose_name="Ставка за урок, ₽",
                    ),
                ),
                (
                    "default_meeting_url",
                    models.URLField(
                        blank=True, verbose_name="Постоянная ссылка на онлайн-класс"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Профиль преподавателя",
                "verbose_name_plural": "Профили преподавателей",
                "ordering": ["sort_order", "user__last_name"],
            },
        ),
    ]
