# Generated by Django 5.2.17 on 2026-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Ученик"),
                    ("teacher", "Преподаватель"),
                    ("admin", "Администратор"),
                    ("owner", "Владелец"),
                ],
                db_index=True,
                default="student",
                max_length=16,
                verbose_name="Роль",
            ),
        ),
    ]
