# Generated by Django 5.2.17 on 2026-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="Сменить пароль при входе"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Логин",
            ),
        ),
    ]
