# Generated by Django 4.2.7 on 2026-08-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_must_change_password_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="notify_parent",
            field=models.BooleanField(
                default=True,
                help_text="Оплата и «заканчивается абонемент» уходят родителю, учёба — ученику.",
                verbose_name="Слать родителю про оплату",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Почта родителя"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Числовой ID чата. Родитель узнаёт его у @userinfobot.",
                max_length=32,
                verbose_name="Telegram ID родителя",
            ),
        ),
    ]
