# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        db_index=True, max_length=2, verbose_name="Уровень"
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("grammar", "Грамматика"),
                            ("vocabulary", "Лексика"),
                            ("reading", "Чтение"),
                            ("usage", "Речевые ситуации"),
                        ],
                        default="grammar",
                        max_length=12,
                        verbose_name="Навык",
                    ),
                ),
                ("prompt", models.CharField(max_length=300, verbose_name="Вопрос")),
                (
                    "hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Пояснение к заданию"
                    ),
                ),
                ("options", models.JSONField(default=list, verbose_name="Варианты")),
                (
                    "correct_index",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Номер верного варианта"
                    ),
                ),
                (
                    "explanation",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Почему так"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="school.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос теста",
                "verbose_name_plural": "Вопросы теста",
                "ordering": ["level", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("current_level", models.CharField(default="A2", max_length=2)),
                ("visited_levels", models.JSONField(blank=True, default=list)),
                ("result_level", models.CharField(blank=True, max_length=2)),
                ("correct_count", models.PositiveSmallIntegerField(default=0)),
                ("total_count", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.language",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placement_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прохождение теста",
                "verbose_name_plural": "Прохождения теста",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chosen_index", models.SmallIntegerField(default=-1)),
                ("is_correct", models.BooleanField(default=False)),
                ("seconds_spent", models.PositiveSmallIntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="placement.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="placement.testsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ в тесте",
                "verbose_name_plural": "Ответы в тесте",
                "ordering": ["answered_at"],
                "unique_together": {("session", "question")},
            },
        ),
    ]
