# Generated by Django 4.2.7 on 2026-08-05 16:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=9,
                        verbose_name="Стоимость урока, ₽",
                    ),
                ),
                ("charged_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "verbose_name": "Списание урока",
                "verbose_name_plural": "Списания уроков",
                "ordering": ["-charged_at"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lessons_total",
                    models.PositiveSmallIntegerField(default=8, verbose_name="Уроков"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость, ₽"
                    ),
                ),
                (
                    "issued_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Выдан"
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("exhausted", "Уроки закончились"),
                            ("expired", "Истёк срок"),
                            ("cancelled", "Аннулирован"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонементы",
                "ordering": ["-issued_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, verbose_name="Название")),
                (
                    "lessons_count",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Уроков в абонементе"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена, ₽"
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="0 — бессрочно.",
                        verbose_name="Срок действия, дней",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=220)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tariffs",
                        to="school.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма, ₽"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("card", "Карта / перевод"),
                            ("bank", "Счёт (юрлицо)"),
                            ("online", "Онлайн-оплата"),
                            ("other", "Другое"),
                        ],
                        default="card",
                        max_length=8,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("paid", "Оплачено"),
                            ("refunded", "Возврат"),
                        ],
                        default="paid",
                        max_length=8,
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата",
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=200)),
                ("provider", models.CharField(blank=True, max_length=32)),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.package",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-paid_on", "-id"],
            },
        ),
    ]
