# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="scheduling.group",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.tariff",
            ),
        ),
        migrations.AddField(
            model_name="lessoncharge",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="billing.package",
            ),
        ),
        migrations.AddField(
            model_name="lessoncharge",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge",
                to="scheduling.lessonparticipant",
            ),
        ),
        migrations.AddField(
            model_name="lessoncharge",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_charges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-paid_on", "status"], name="billing_pay_paid_on_0efc55_idx"
            ),
        ),
    ]
