# Generated by Django 4.2.7 on 2026-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Карточка получает подпись «чаще всего выбирают».",
                verbose_name="Выделить на главной",
            ),
        ),
    ]
