# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Задание")),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок сдачи"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Максимум баллов"
                    ),
                ),
                (
                    "requires_submission",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите, если задание «прочитать/послушать» без отправки ответа.",
                        verbose_name="Нужно сдать работу",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Название модуля"),
                ),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("order", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Тема")),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "objectives",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку.",
                        verbose_name="Цели урока",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Конспект / план"),
                ),
                (
                    "vocabulary",
                    models.TextField(
                        blank=True,
                        help_text="word — перевод, по строке на слово.",
                        verbose_name="Лексика",
                    ),
                ),
                ("estimated_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="learning.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юнит",
                "verbose_name_plural": "Юниты",
                "ordering": ["module__order", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Назначено"),
                            ("submitted", "Сдано"),
                            ("reviewed", "Проверено"),
                            ("redo", "На доработку"),
                        ],
                        default="assigned",
                        max_length=12,
                    ),
                ),
                ("answer_text", models.TextField(blank=True, verbose_name="Ответ")),
                (
                    "answer_file",
                    models.FileField(
                        blank=True, null=True, upload_to="submissions/%Y/%m/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "teacher_feedback",
                    models.TextField(
                        blank=True, verbose_name="Комментарий преподавателя"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="learning.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа ученика",
                "verbose_name_plural": "Работы учеников",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Название программы"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A0", "A0 · Beginner"),
                            ("A1", "A1 · Elementary"),
                            ("A2", "A2 · Pre-Intermediate"),
                            ("B1", "B1 · Intermediate"),
                            ("B2", "B2 · Upper-Intermediate"),
                            ("C1", "C1 · Advanced"),
                            ("C2", "C2 · Proficiency"),
                        ],
                        max_length=2,
                        verbose_name="Уровень",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_shared",
                    models.BooleanField(
                        default=True,
                        help_text="Общая библиотека школы — программу можно взять за основу.",
                        verbose_name="Доступна другим преподавателям",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="school.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
                "ordering": ["language__name", "level", "title"],
            },
        ),
        migrations.AddField(
            model_name="module",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="learning.program",
            ),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Название")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "Файл"),
                            ("link", "Ссылка"),
                            ("video", "Видео"),
                            ("audio", "Аудио"),
                            ("text", "Текст"),
                        ],
                        default="link",
                        max_length=8,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="materials/%Y/%m/"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="learning.assignment",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="learning.unit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ["order", "id"],
            },
        ),
    ]
