# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0001_initial"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="scheduling.group",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="scheduling.lesson",
                verbose_name="Выдано на уроке",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="learning.unit",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("assignment", "student")},
        ),
    ]
