# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=220)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Вопрос-ответ",
                "verbose_name_plural": "Вопросы и ответы",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Язык")),
                ("slug", models.SlugField(unique=True)),
                (
                    "flag_code",
                    models.CharField(
                        default="gb",
                        help_text="ISO 3166-1 alpha-2",
                        max_length=4,
                        verbose_name="Код флага",
                    ),
                ),
                (
                    "short_pitch",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Короткое описание"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Название")),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "city",
                    models.CharField(
                        default="Красноярск", max_length=80, verbose_name="Город"
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(blank=True, verbose_name="Карта (iframe src)"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Онлайн-площадка"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
                "ordering": ["-is_online", "name"],
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Заголовок")),
                ("slug", models.SlugField(unique=True)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подзаголовок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Условия")),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Например: −20%",
                        max_length=40,
                        verbose_name="Плашка",
                    ),
                ),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-starts_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="Лингвич", max_length=60)),
                (
                    "tagline",
                    models.CharField(
                        default="Языковая школа в Красноярске", max_length=140
                    ),
                ),
                (
                    "phone",
                    models.CharField(default="+7 (391) 214-73-03", max_length=32),
                ),
                ("email", models.EmailField(default="linguich@ya.ru", max_length=254)),
                ("telegram_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True)),
                ("vk_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "hero_title",
                    models.CharField(
                        default="Язык, на котором вы наконец заговорите", max_length=160
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Английский, немецкий, китайский и ещё пять языков — в группах, индивидуально и онлайн.",
                        max_length=240,
                    ),
                ),
                (
                    "notify_leads_to",
                    models.EmailField(
                        blank=True,
                        help_text="Куда присылать уведомления о новых заявках.",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "author_role",
                    models.CharField(
                        blank=True,
                        help_text="Например: мама ученика, 8 лет",
                        max_length=120,
                        verbose_name="Кто",
                    ),
                ),
                ("text", models.TextField(verbose_name="Отзыв")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, verbose_name="Оценка"),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="reviews/"),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="school.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("group", "Группа"),
                            ("individual", "Индивидуально"),
                            ("pair", "Пара / мини-группа"),
                            ("club", "Разговорный клуб"),
                            ("kids", "Дети"),
                            ("exam", "Подготовка к экзамену"),
                            ("corporate", "Корпоративный"),
                        ],
                        default="group",
                        max_length=16,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "level_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A0", "A0 · Beginner"),
                            ("A1", "A1 · Elementary"),
                            ("A2", "A2 · Pre-Intermediate"),
                            ("B1", "B1 · Intermediate"),
                            ("B2", "B2 · Upper-Intermediate"),
                            ("C1", "C1 · Advanced"),
                            ("C2", "C2 · Proficiency"),
                        ],
                        max_length=2,
                        verbose_name="Уровень от",
                    ),
                ),
                (
                    "level_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A0", "A0 · Beginner"),
                            ("A1", "A1 · Elementary"),
                            ("A2", "A2 · Pre-Intermediate"),
                            ("B1", "B1 · Intermediate"),
                            ("B2", "B2 · Upper-Intermediate"),
                            ("C1", "C1 · Advanced"),
                            ("C2", "C2 · Proficiency"),
                        ],
                        max_length=2,
                        verbose_name="Уровень до",
                    ),
                ),
                (
                    "age_from",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Возраст от"
                    ),
                ),
                (
                    "age_to",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Возраст до"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="Короткое описание"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "outcomes",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку.",
                        verbose_name="Результаты",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Длительность урока, мин"
                    ),
                ),
                (
                    "lessons_per_week",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Занятий в неделю"
                    ),
                ),
                (
                    "price_per_lesson",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="Цена за урок, ₽",
                    ),
                ),
                (
                    "is_online_available",
                    models.BooleanField(default=True, verbose_name="Есть онлайн"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="На главной"),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="school.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "preferred_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("group", "Группа"),
                            ("individual", "Индивидуально"),
                            ("pair", "Пара / мини-группа"),
                            ("club", "Разговорный клуб"),
                            ("kids", "Дети"),
                            ("exam", "Подготовка к экзамену"),
                            ("corporate", "Корпоративный"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("trial", "Форма записи"),
                            ("callback", "Обратный звонок"),
                            ("placement", "Тест уровня"),
                            ("course", "Страница курса"),
                            ("phone", "Звонок"),
                            ("offline", "Пришли в офис"),
                            ("other", "Другое"),
                        ],
                        default="trial",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("scheduled", "Записан на пробный"),
                            ("won", "Стал учеником"),
                            ("lost", "Отказ"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "placement_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A0", "A0 · Beginner"),
                            ("A1", "A1 · Elementary"),
                            ("A2", "A2 · Pre-Intermediate"),
                            ("B1", "B1 · Intermediate"),
                            ("B2", "B2 · Upper-Intermediate"),
                            ("C1", "C1 · Advanced"),
                            ("C2", "C2 · Proficiency"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Комментарий"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.course",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="school_lead_status_df4f2d_idx",
                    )
                ],
            },
        ),
    ]
