# Generated by Django 4.2.7 on 2026-08-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="founder_name",
            field=models.CharField(
                blank=True,
                default="Глухова Евгения Алексеевна",
                max_length=120,
                verbose_name="Основатель: имя",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="founder_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                verbose_name="Основатель: фото",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="founder_quote",
            field=models.TextField(
                blank=True,
                default="Я открыла «Лингвич» в 2011 году, потому что верю: язык учат разговором, а не зубрёжкой правил. Мы не гонимся за количеством — я лично знаю каждого преподавателя и вижу, как идут дела у каждой группы.",
                verbose_name="Основатель: обращение",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="founder_role",
            field=models.CharField(
                blank=True,
                default="основатель школы, преподаватель английского",
                max_length=140,
                verbose_name="Основатель: должность",
            ),
        ),
    ]
