# Generated by Django 5.2.17 on 2026-08-10 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school",
            "0002_sitesettings_founder_name_sitesettings_founder_photo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ip",
            field=models.CharField(blank=True, db_index=True, max_length=45),
        ),
        migrations.AddField(
            model_name="lead",
            name="user_agent",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["ip", "-created_at"], name="school_lead_ip_e69b8c_idx"
            ),
        ),
    ]
