# Generated by Django 5.2.17 on 2026-08-22 13:37

from django.db import migrations, models


# Знак алфавита и цвет линии для языков, которые школа уже преподаёт. Заполняем
# при миграции, чтобы схема маршрутов заработала сразу, а не ждала, пока кто-то
# зайдёт в админку. Всё, что школа заведёт дальше, редактируется там же.
SEEDED = {
    "english": ("A", "#008CD2"),
    "chinese": ("\u6587", "#E2543C"),
    "german": ("\u00c4", "#F2B134"),
    "french": ("\u00c7", "#7C5CD6"),
    "korean": ("\ud55c", "#2FB98A"),
    "turkish": ("\u015e", "#E8657F"),
    "czech": ("\u010c", "#4E7FA8"),
}


def fill_line_style(apps, schema_editor):
    Language = apps.get_model("school", "Language")
    for slug, (glyph, color) in SEEDED.items():
        Language.objects.filter(slug=slug).update(glyph=glyph, line_color=color)


def clear_line_style(apps, schema_editor):
    Language = apps.get_model("school", "Language")
    Language.objects.filter(slug__in=SEEDED).update(glyph="", line_color="")


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_lead_ip_lead_user_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="glyph",
            field=models.CharField(
                blank=True,
                help_text="Один знак для первого экрана: A, Ä, 文, 한. Пусто — возьмём первую букву названия.",
                max_length=4,
                verbose_name="Буква алфавита",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="line_color",
            field=models.CharField(
                blank=True,
                help_text="HEX вида #008CD2 — цвет языка на схеме маршрутов. Пусто — возьмём из палитры.",
                max_length=7,
                verbose_name="Цвет линии",
            ),
        ),
        migrations.RunPython(fill_line_style, clear_line_style),
    ]
