# Generated by Django 4.2.7 on 2026-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_lead_ip_lead_user_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Например «2ГИС» или «Яндекс Карты». Пусто — просто отзыв на сайте.",
                max_length=40,
                verbose_name="Откуда отзыв",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="source_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на отзыв"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="rating_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отзывов на площадке"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="rating_source",
            field=models.CharField(
                blank=True, default="2ГИС", max_length=40, verbose_name="Площадка"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="rating_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на отзывы"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="rating_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Например 4.9. Пусто — блок с оценкой не показывается.",
                max_digits=2,
                null=True,
                verbose_name="Оценка на площадке",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="since_year",
            field=models.PositiveSmallIntegerField(
                default=2011, verbose_name="Работаем с"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="students_total",
            field=models.CharField(
                blank=True,
                default="1 400+",
                help_text="Как показывать: «1 400+». Пишется словом, а не числом, — это витрина.",
                max_length=20,
                verbose_name="Учеников всего",
            ),
        ),
    ]
