# Generated by Django 5.2.17 on 2026-08-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_language_glyph_language_line_color"),
        ("school", "0004_review_source_review_source_url_and_more"),
    ]

    operations = []
