# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "mode",
                    models.CharField(
                        choices=[("offline", "В классе"), ("online", "Онлайн")],
                        default="offline",
                        max_length=8,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A0", "A0 · Beginner"),
                            ("A1", "A1 · Elementary"),
                            ("A2", "A2 · Pre-Intermediate"),
                            ("B1", "B1 · Intermediate"),
                            ("B2", "B2 · Upper-Intermediate"),
                            ("C1", "C1 · Advanced"),
                            ("C2", "C2 · Proficiency"),
                        ],
                        max_length=2,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(default=8, verbose_name="Мест"),
                ),
                (
                    "meeting_url",
                    models.URLField(blank=True, verbose_name="Ссылка на онлайн-класс"),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, null=True, verbose_name="Старт"),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="Окончание"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="school.course",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.location",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="learning.program",
                        verbose_name="Учебная программа",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["teacher", "owner"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=180, verbose_name="Тема"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(db_index=True, verbose_name="Начало"),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Длительность, мин"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("offline", "В классе"), ("online", "Онлайн")],
                        default="offline",
                        max_length=8,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(blank=True, verbose_name="Ссылка на онлайн-класс"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Мест"),
                ),
                (
                    "is_trial",
                    models.BooleanField(default=False, verbose_name="Пробный урок"),
                ),
                (
                    "is_bookable",
                    models.BooleanField(
                        default=False, verbose_name="Доступен для самозаписи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("completed", "Проведён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                (
                    "teacher_note",
                    models.TextField(blank=True, verbose_name="Заметка преподавателя"),
                ),
                ("cancelled_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="scheduling.group",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.location",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["teacher", "owner"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="learning.unit",
                        verbose_name="Юнит программы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="С")),
                ("ends_at", models.DateTimeField(verbose_name="До")),
                ("reason", models.CharField(blank=True, max_length=140)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Недоступность",
                "verbose_name_plural": "Недоступность",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="С")),
                ("end_time", models.TimeField(verbose_name="До")),
                (
                    "slot_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Шаг слота, мин"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("offline", "В классе"), ("online", "Онлайн")],
                        default="online",
                        max_length=8,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.location",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["teacher", "owner"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Окно записи",
                "verbose_name_plural": "Окна записи",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("ended_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="scheduling.group",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Зачисление",
                "verbose_name_plural": "Зачисления",
                "ordering": ["-started_on"],
            },
        ),
        migrations.CreateModel(
            name="RecurringSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Начало")),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Длительность, мин"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="scheduling.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот расписания",
                "verbose_name_plural": "Слоты расписания",
                "ordering": ["weekday", "start_time"],
                "unique_together": {("group", "weekday", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="LessonParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Записан"),
                            ("attended", "Был"),
                            ("absent", "Не пришёл"),
                            ("excused", "Отменил заранее"),
                            ("cancelled", "Запись отменена"),
                        ],
                        default="booked",
                        max_length=12,
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_chargeable",
                    models.BooleanField(
                        default=True,
                        help_text="Снимается, если ученик отменил заранее или урок отменила школа.",
                        verbose_name="Списывать урок",
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, verbose_name="Комментарий по уроку"),
                ),
                (
                    "performance",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1–5, видна ученику.",
                        null=True,
                        verbose_name="Оценка активности",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник урока",
                "verbose_name_plural": "Участники уроков",
                "ordering": ["student__last_name"],
                "unique_together": {("lesson", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["teacher", "starts_at"], name="scheduling__teacher_d36fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["status", "starts_at"], name="scheduling__status_01e489_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "group")},
        ),
    ]
