# Generated by Django 4.2.7 on 2026-08-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отмечен проведённым"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — урок отметился сам, когда прошло время, и человек этого ещё не подтвердил.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons_completed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подтвердил",
            ),
        ),
    ]
