# Generated by Django 4.2.7 on 2026-08-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lesson_reminder", "Напоминание об уроке"),
                            ("lesson_cancelled", "Урок отменён"),
                            ("lesson_booked", "Запись на урок"),
                            ("homework_assigned", "Новое домашнее задание"),
                            ("homework_reviewed", "Домашка проверена"),
                            ("homework_submitted", "Ученик сдал домашку"),
                            ("package_low", "Заканчивается абонемент"),
                            ("payment_due", "Напоминание об оплате"),
                            ("payment_received", "Платёж получен"),
                            ("new_lead", "Новая заявка"),
                            ("custom", "Произвольное"),
                        ],
                        default="custom",
                        max_length=24,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("inapp", "В кабинете"),
                        ],
                        default="inapp",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                            ("skipped", "Пропущено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True, max_length=140, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_d8d933_idx",
                    )
                ],
            },
        ),
    ]
